= Zeke Soh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction
Hello, my name is Zeke. At the time of this project (AY19/20), I was a Year 2 Computer Science undergraduate at the National University of Singapore. Additionally, I am a software developer in Team Volant. That's the team that is working on this
wonderful travel companion app! We're really passionate about this project, so we hope that you enjoy the product
as much as we enjoy the process.

You can find out more about who I am at these links:

* https://www.linkedin.com/in/zsoh97/[My LinkedIn profile]
* https://www.github.com/zsoh97[My github profile]

== PROJECT: Volant

Volant is a travel assistant desktop application aimed at assisting solo travellers with the logistics of planning
their travels. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java and
it is primarily based off of the Address Book 3 application developed by the CS2103T teaching team.

=== Summary of Contributions
You can view my code contributions to this project
https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=zsoh97&sort=totalCommits%20dsc&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[on RepoSense].

* *Major Enhancement:* Implemented storage for the entire project.
** What it does: Allowed users to save and load their data when using the project.
** Highlights: The implementation of the storage was a bottleneck for our team project as in order to
implement and test the functionalities of our features, developers had to have data to work with.

* *Major Enhancement:* Implemented the Itinerary page (with Nguyen).
** What it does: Allows users to view and manipulate the itinerary activities in the application.

* *Major Enhancement:* Implemented exceptions for catching logic bugs for Trip and Itinerary feature.
** Justification: In placing these exceptions, the functionality of the project is not compromised.
** What it does: Catches logically invalid commands that the user may enter. E.g. The timing for an activity in the itinerary being outside of the date range of the trip.

* *Major Enhancement:* Implemented the GUI for the application.

* *Testing:* Did JUnit testing for `ITINERARY` (with Zeke)
** Highlights: I added JUnit tests for itinerary's commands and parsers, while Zeke
added JUnit tests for itinerary's model and storage.

* *Other Contributions*
** Documentation
*** Did cosmetic tweaks to existing contents of the User Guide:
*** PRs reviewed(with non-trivial review comments):

=== Contributions to User Guide
==== Sections Written
* Transferred early stage user guide in google doc to adoc.
* https://github.com/AY1920S2-CS2103T-F09-4/main/blob/master/docs/UserGuide.adoc#1-introduction[Section 1. Introduction]
* https://github.com/AY1920S2-CS2103T-F09-4/main/blob/master/docs/UserGuide.adoc#3-features[Section 3. Features]
* https://github.com/AY1920S2-CS2103T-F09-4/main/blob/master/docs/UserGuide.adoc#commands-for-the-home-page[Section 4.4. Commands for the Home Page]
* Formatted command summary to table form

=== Contributions to Developer Guide
==== Sections Written
*gotoBackCommand sequence diagram for Views in Volant.
*UML diagram for storage component.
*UML diagram for delete command.
*UML diagram for refresh command.
*UML diagram for storage when adding a new trip.
*UML diagram for storage when adding a new activity.

_{To be updated in the future}_
